services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_todo
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
